### ISSUE TITLE
Make page scaling slightly smaller (more closely match the mockup)

### ISSUE THREAD

**Issue by hananiah42** [danielrw7/book-calculator#15]
This is because the current scaling (on Windows 10 Chrome) is slightly too large, making content not fit on the screen as well.

**Comment by weaversam8** [comment]
Could you elaborate which elements you'd like to change?

**Comment by hananiah42** [comment]
The scaling of the page is much larger than the mockup, at least for me viewing it in Chrome. When I scale to 80%, it looks more like the mockup. I can attach screenshots if needed.

**Comment by weaversam8** [comment]
Please do. The term "scaling of the page" could mean many things... could you indicate whether you're talking about spacing between components, about font sizes, about something else?
